version: "3.5"

services:
    nginx:
        container_name: ${APP_NAME}-nginx
        build:
            context: nginx
            args:
                UID: $U_ID
                APP_NAME: ${APP_NAME}
        ports:
            - "8080:80"
        volumes:
            - ${APP_PATH}/public:/var/www/html/public
        depends_on:
            - php
        networks:
            - default
    php:
        container_name: ${APP_NAME}-php
        build:
            context: php
            args:
                UID: $U_ID
                TIMEZONE: America/Lima
        volumes:
            - ${APP_PATH}:/var/www/html:cached
            - ~/.ssh/id_rsa./:/home/appuser/.ssh/id_rsa
        ###> XDEBUG 3 ###
        # Use your client IP here
        # Linux: run "ip a | grep docker0"
        environment:
            XDEBUG_CLIENT_HOST: 172.17.0.1
            XDEBUG_CLIENT_PORT: 9003
            PHP_IDE_CONFIG: serverName=${APP_NAME}
        networks:
            - default

    mysql:
        container_name: ${APP_NAME}-mysql
        build:
            context: mysql
        ports:
            - "6602:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - default
        command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]

volumes:
    mysql-data:
        name: ${APP_NAME}_mysql-data

networks:
    default:
        name: default-network
        external: true